COLUMNS:
  _id: object
  "Unnamed: 0": int
  since_last_ns: int
  timestamp_ms: int
  current_engine_rpm: float
  wheel_rotation_speed_front_left: float
  wheel_rotation_speed_front_right: float
  wheel_rotation_speed_rear_left: float
  wheel_rotation_speed_rear_right: float
  wheel_on_rumble_strip_front_left: bool
  wheel_on_rumble_strip_front_right: bool
  wheel_on_rumble_strip_rear_left: bool
  wheel_on_rumble_strip_rear_right: bool
  wheel_in_puddle_depth_front_left: int
  wheel_in_puddle_depth_front_right: int
  wheel_in_puddle_depth_rear_left: int
  wheel_in_puddle_depth_rear_right: int
  tire_slip_rotation_front_left: float
  tire_slip_rotation_front_right: float
  tire_slip_rotation_rear_left: float
  tire_slip_rotation_rear_right: float
  tire_slip_angle_front_left: float
  tire_slip_angle_front_right: float
  tire_slip_angle_rear_left: float
  tire_slip_angle_rear_right: float
  tire_combined_slip_front_left: float
  tire_combined_slip_front_right: float
  tire_combined_slip_rear_left: float
  tire_combined_slip_rear_right: float
  tire_temp_front_left: float
  tire_temp_front_right: float
  tire_temp_rear_left: float
  tire_temp_rear_right: float
  normalized_suspension_travel_front_left: float
  normalized_suspension_travel_front_right: float
  normalized_suspension_travel_rear_left: float
  normalized_suspension_travel_rear_right: float
  suspension_travel_meters_front_left: float
  suspension_travel_meters_front_right: float
  suspension_travel_meters_rear_left: float
  suspension_travel_meters_rear_right: float
  position_x: float
  position_y: float
  position_z: float
  acceleration_x: float
  acceleration_y: float
  acceleration_z: float
  velocity_x: float
  velocity_y: float
  velocity_z: float
  angular_velocity_x: float
  angular_velocity_y: float
  angular_velocity_z: float
  yaw: float
  pitch: float
  roll: float
  speed: float
  power: float
  torque: float
  boost: float
  fuel: float
  distance_traveled: float
  acceleration: int
  brake: int
  clutch: int
  handbrake: int
  gear: int
  steer: int
  lap_number: int
  best_lap_time: float
  last_lap_time: float
  current_lap_time: float
  current_race_time: float
  race_position: int